import moment from "moment";
moment.locale("ko");
export const wholePrice = {
  recent: [
    {
      kind: "품종1",
      unit: "10kg",
      high: 12000,
      middle: 10000,
    },
    {
      kind: "품종2",
      unit: "100개",
      high: null,
      middle: 10000,
    },
    {
      kind: "품종3",
      unit: "20kg",
      high: 12000,
      middle: null,
    },
  ],
  prev: [
    {
      kind: "품종1",
      unit: "10kg",
      high: 12000,
      middle: 10000,
    },
    {
      kind: "품종2",
      unit: "100개",
      high: null,
      middle: 10000,
    },
    {
      kind: "품종3",
      unit: "20kg",
      high: 12000,
      middle: null,
    },
  ],
};

export const retailPrice = {
  recent: [
    {
      kind: "품종1",
      unit: "10kg",
      high: {
        min: 1000,
        max: 2000,
      },
      middle: {
        min: 800,
        max: 1500,
      },
    },
    {
      kind: "품종2",
      unit: "100개",
      high: null,
      middle: {
        min: 800,
        max: 1500,
      },
    },
    {
      kind: "품종3",
      unit: "20kg",
      high: {
        min: 1000,
        max: 2000,
      },
      middle: null,
    },
  ],
  prev: [
    {
      kind: "품종1",
      unit: "10kg",
      high: {
        min: 1000,
        max: 2000,
      },
      middle: {
        min: 800,
        max: 1500,
      },
    },
    {
      kind: "품종2",
      unit: "100개",
      high: null,
      middle: {
        min: 800,
        max: 1500,
      },
    },
    {
      kind: "품종3",
      unit: "20kg",
      high: {
        min: 1000,
        max: 2000,
      },
      middle: null,
    },
  ],
};

export const newsData = [
  {
    title: "뉴스기사 1",
    source: "언론사 1",
    createdAt: "20.00.01",
  },
  {
    title: "뉴스기사 2",
    source: "언론사 2",
    createdAt: "20.00.02",
  },
  {
    title: "뉴스기사 3",
    source: "언론사 3",
    createdAt: "20.00.03",
  },
];

export const youtubeData = [
  {
    title: "제목",
    channel: "채널 1",
    createdAt: "20.00.01",
  },
  {
    title: "제목",
    channel: "채널 2",
    createdAt: "20.00.02",
  },
  {
    title: "제목",
    channel: "채널 3",
    createdAt: "20.00.03",
  },
];

export function getGoogleChartData() {
  const data = chartData.map((item) => {
    const date = new Date(moment(item.ExaminDate).format("YYYY-MM-DD"));
    return [date, item.MinPrice];
  });
  console.log("data", data);
  return data;
}

export const chartData = [
  {
    ExaminDate: "2020-01-09",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-10",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-11",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-12",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-13",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-14",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-15",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-16",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-17",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-18",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-19",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-20",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-21",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-22",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-23",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-24",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-25",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-26",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-28",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-29",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-30",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-01-31",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-01",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-02",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-04",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-05",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-06",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-07",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-08",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-09",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-10",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-11",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-12",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-13",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-14",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-15",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-16",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-17",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-18",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-19",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-20",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-21",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-22",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-23",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-24",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-25",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-26",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-27",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-28",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-02-29",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-01",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-02",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-03",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-04",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-05",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-06",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-07",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-08",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-09",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-10",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-11",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-12",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-13",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-14",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-15",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-16",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-17",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-18",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-19",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-20",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-21",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-22",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-23",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-24",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-25",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-26",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-27",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-28",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-29",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-30",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-03-31",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-01",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-02",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-03",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-04",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-05",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-06",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-07",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-08",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-09",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-10",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-11",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-12",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-13",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-14",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-15",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-16",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-17",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-18",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-19",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-20",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-21",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-22",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-23",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-24",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-25",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-26",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-27",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-28",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-29",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-04-30",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-01",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-02",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-04",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-05",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-06",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-07",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-08",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-09",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-10",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-11",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-12",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-13",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-14",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-15",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-16",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-17",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-18",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-19",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-20",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-21",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-22",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-23",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-24",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-25",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50300,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-26",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-27",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-28",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-29",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-30",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-05-31",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-06-01",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-06-02",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-06-03",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-06-04",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-06-05",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-06-06",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-06-07",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-06-08",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53000,
  },
  {
    ExaminDate: "2020-06-09",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-10",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-11",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-12",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-13",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-14",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-15",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-16",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-17",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-18",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-19",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-20",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-21",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-22",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-23",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-24",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-25",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-26",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-27",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-28",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-29",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-06-30",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-01",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-02",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-03",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-04",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-05",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-06",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-07",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-08",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-09",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-10",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-11",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-12",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-13",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-14",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-15",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 50600,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-16",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-17",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-18",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-19",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-20",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-21",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-22",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-23",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-24",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-25",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-26",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-27",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-28",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-29",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-30",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-07-31",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-01",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-02",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-03",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-04",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-05",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-06",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-07",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-08",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-09",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-10",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-11",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-12",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-13",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-14",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-15",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-16",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-17",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-18",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-19",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-20",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-21",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-22",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-23",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-24",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-25",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-26",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 53300,
  },
  {
    ExaminDate: "2020-08-27",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-08-28",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-08-29",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-08-30",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-08-31",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-01",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-02",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-03",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-04",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-05",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-06",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-07",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51000,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-08",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-09",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-10",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-11",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-12",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-13",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 51300,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-14",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-15",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-16",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-17",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-18",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-19",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-20",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-21",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-22",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-23",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-24",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
  {
    ExaminDate: "2020-09-25",
    ExaminItemName: "쌀",
    ExaminItemCode: "111",
    ExaminSpeciesName: "일반계",
    ExaminSpeciesCode: "01",
    ExaminUnitName: "20KG",
    ExaminUnit: "20",
    ExaminGradeName: "상(1등급)",
    ExaminGradeCode: "1",
    MinPrice: 52600,
    MaxPrice: 54000,
  },
];
